[default]
# Spell checker configuration for vb-cli
# https://github.com/crate-ci/typos

# Files to check
extend-glob = ["*.md", "*.txt", "*.yaml", "*.yml", "*.go"]

# Files to ignore
[files]
extend-exclude = [
  "coverage.out",
  "go.sum",
  "dist/",
  ".git/",
  "vendor/",
  "*.log",
]

[default.extend-words]
# Project-specific terms
vb = "vb"
cli = "cli"
virtualboard = "virtualboard"
VirtualBoard = "VirtualBoard"
golang = "golang"
gosec = "gosec"
gofmt = "gofmt"
gomod = "gomod"
semver = "semver"
yaml = "yaml"
json = "json"
api = "api"
url = "url"
http = "http"
https = "https"
github = "github"
linux = "linux"
macos = "macos"
amd = "amd"
arm = "arm"
intel = "intel"
homebrew = "homebrew"
workflow = "workflow"
workflows = "workflows"
dockerfile = "dockerfile"
kubernetes = "kubernetes"
k8s = "k8s"
oauth = "oauth"
jwt = "jwt"
uuid = "uuid"
timestamp = "timestamp"
checkbox = "checkbox"
checkboxes = "checkboxes"
screenshot = "screenshot"
screenshots = "screenshots"
config = "config"
configs = "configs"
mutex = "mutex"
struct = "struct"
structs = "structs"
func = "func"
funcs = "funcs"
middleware = "middleware"
repo = "repo"
repos = "repos"
sha = "sha"
changelog = "changelog"
readme = "readme"
makefile = "makefile"
gitignore = "gitignore"
precommit = "precommit"
linter = "linter"
linters = "linters"
validator = "validator"
validators = "validators"
indexer = "indexer"
indexers = "indexers"

# Common technical abbreviations
ui = "ui"
ux = "ux"
pr = "pr"
prs = "prs"
ci = "ci"
cd = "cd"
db = "db"
os = "os"
fs = "fs"
io = "io"
tcp = "tcp"
udp = "udp"
ip = "ip"
dns = "dns"
ssl = "ssl"
tls = "tls"
cpu = "cpu"
ram = "ram"
gpu = "gpu"
ssd = "ssd"
vm = "vm"
vms = "vms"

[type.go]
# Go-specific corrections
extend-glob = ["*.go"]

[type.go.extend-words]
# Go-specific terms
func = "func"
var = "var"
const = "const"
struct = "struct"
interface = "interface"
package = "package"
import = "import"
return = "return"
defer = "defer"
go = "go"
chan = "chan"
select = "select"
switch = "switch"
case = "case"
default = "default"
fallthrough = "fallthrough"
break = "break"
continue = "continue"
goto = "goto"
if = "if"
else = "else"
for = "for"
range = "range"
type = "type"
map = "map"
slice = "slice"
array = "array"
string = "string"
int = "int"
int8 = "int8"
int16 = "int16"
int32 = "int32"
int64 = "int64"
uint = "uint"
uint8 = "uint8"
uint16 = "uint16"
uint32 = "uint32"
uint64 = "uint64"
float32 = "float32"
float64 = "float64"
bool = "bool"
byte = "byte"
rune = "rune"
error = "error"
nil = "nil"
true = "true"
false = "false"
iota = "iota"
